server:
   port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle
    username: root
    password: Root   
     
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect